name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Verificar o código do repositório
      - name: Checkout Code
        uses: actions/checkout@v3

      # Passo 2: Configurar o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  

      # Passo 3: Instalar as dependências
      - name: Install dependencies
        run: npm install

      # Passo 4: Rodar os testes
      - name: Run Tests
        run: npm run test

      # Passo 5: Build da aplicação (apenas se os testes passarem)
      - name: Build Application
        run: npm run build

      # Passo 6: Instalar a versão mais recente do Vercel CLI
      - name: Install Latest Vercel CLI
        run: npm install -g vercel

      # Passo 7: Deploy no Vercel
      - name: Deploy to Vercel
        run: npx vercel --prod --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          